### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement shapash

### ISSUE THREAD

**Issue by Vaderv** [MAIF/shapash#116]
Hey there and thank you for using Issue Tracker!

Do the checklist before filing an issue:

- Is this something you can debug and fix? Send a pull request ! Bug fixes and documentation fixes are welcome.
- Have a usage question ? Ask your question on StackOverflow. We use StackOverflow for usage question and GitHub for bugs.

None of the above, create a bug report

Make sure to add all the information needed to understand the bug so that someone can help. If the info is missing we'll add the 'Needs more information' label and close the issue until there is enough information.

- Provide a minimal code snippet example that reproduces the bug.
- Provide screenshots where appropriate
- What's the version of Python you're using ?
- Are you using Mac, Linux or Windows?

**Python version** :

**Shapash version** :

**Operating System** :

**Comment by yg79** [comment]
Shapash is now available with python 3.6 / 3.7 / 3.8 

If you are working with jupyter, use the following commands in a terminal to create a 3.8 environment:

conda create shpenv python=3.7
source activate shpenv
pip install shapash
