### ISSUE TITLE
Interaction Values - SmartPlotter - add method plot_scatter_interactions

### ISSUE THREAD

**Issue by ThibaudReal** [MAIF/shapash#122]
**Description of Problem**:
- Implement a plot to observe interactions between two variables and their corresponding shap values.
See here for more information about what is already implemented in shap : https://slundberg.github.io/shap/notebooks/NHANES%20I%20Survival%20Model.html
The goal here would be to reproduce the scatter plots in plotly to have better understanding of the interactions between two variables, which is not possible in shapash right now.

**Overview of the Solution**:
The plot_scatter_interactions method could :
- Re-use the plot_scatter function of the SmartPlotter object
- Use the get_interaction_values method of the SmartExplainer object (see #120 )

**Comment by yg79** [comment]
I think you should also re-use plot_violin method for categorical features.
