### ISSUE TITLE
Issue with xpl.plot.contribution_plot() method after loading serialized SmartExplainer

### ISSUE THREAD

**Issue by chetanambi** [MAIF/shapash#131]
Hi - 

When running contribution_plot() on SmartExplainer object it works fine. But once you serialize it, load it and then try contribution_plot() it giving below error. I was trying this for Wine Quality dataset and facing this issue.

xpl.save('WineQuality_xpl.pkl')

```
xpl = SmartExplainer()
xpl.load('WineQuality_xpl.pkl')
xpl.plot.contribution_plot("alcohol")
```

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-14-17643c0a90cf> in <module>
----> 1 xpl.plot.contribution_plot("alcohol")

c:\users\chetan_ambi\.conda\envs\shapash\lib\site-packages\shapash\explainer\smart_plotter.py in contribution_plot(self, col, selection, label, violin_maxf, max_points, proba, width, height, file_name, auto_open)
   1081 
   1082         # Subset
-> 1083         if self.explainer.postprocessing_modifications:
   1084             feature_values = self.explainer.x_contrib_plot.loc[list_ind, col_name].to_frame()
   1085         else:

AttributeError: 'SmartExplainer' object has no attribute 'postprocessing_modifications'
```

**Python version** : 3.8.5
**Shapash version** : 1.1.0
**Operating System** :  Windows 10 64-bit

**Comment by ThibaudReal** [comment]
Hello @chetanambi and thank you for reporting this bug.

This issue is actually the same as issue #133 and is due to some attributes not being properly saved. 
We are currently working on a fix that will be available soon.

Thanks again for all your contributions.

The Shapash Team

**Comment by yg79** [comment]
Hello @chetanambi 
We will deploy a new version of Shapash next week which will fix the bug.
Thank you!
Yann
