### ISSUE TITLE
C extension was not built during install!

### ISSUE THREAD

**Issue by paulineolivierMFG** [MAIF/shapash#151]
Hello, 

I try to reproduce `tutorial01-Shapash-Overview-Launch-WebApp.ipynb` with my own dataset and model (`RandomForestClassifier`) but I have this error `C extension was not built during install!` when I run the `.compile`.

Thanks, Pauline.

**Comment by yg79** [comment]
Hello Pauline,

Do you use scikit-learn scikit-learn 0.24.1?
Shapash is now available with scikit-learn==0.23.2
**pip install scikit-learn==0.23.2**

**Comment by paulineolivierMFG** [comment]
Hello, 

I have the error with the version 0.23.2 of sklearn

**Comment by yg79** [comment]
Hello Pauline,
Did you create a venv to run the tutorial?
Can you please freeze the env you use and send us the requirement.txt
**pip freeze > requirements.txt**
