### ISSUE TITLE
Digit counter breaks on 0

### ISSUE THREAD

**Issue by DragonWarrior15** [MAIF/shapash#156]
**Python version** : 3.6.2

**Shapash version** : 1.2.0

**Operating System** : Windows

The following piece of [code](https://github.com/MAIF/shapash/blob/d2a5e466450e8bef1e2eac055d78773747244489/shapash/utils/utils.py#L140) breaks

```py
def compute_digit_number(value):
    """
    return int, number of digits to display
    Parameters
    ----------
    value : float
        can be the gap between percentiles
    Returns
    -------
    int
        number of digits
    """
    first_nz = int(math.log10(abs(value)))
    digit = abs(min(3,first_nz) - 3)
    return digit
```

when the variable `value` is zero (I got `ValueError: math domain error`). Due to this, the two charts showing local feature importance for a single row ID, and the chart showing the trend of feature importance of a single feature were not rendered.

I could fix the issue by adding the below conditional
```py
    if(abs(value) == 0):
        first_nz = 1
    else:
        first_nz = int(math.log10(abs(value)))
    digit = abs(min(3,first_nz) - 3)
    return digit
```
and the charts were fully rendered after the fix.

Please let me know if this is indeed a complete fix and I can add a pull request with this change.

**Comment by yg79** [comment]
Hello DragonWarrior15,

You can of course fix this bug by following the contribut.md file from the shapash repository (fork, PR, test, ...)
I think you should use 
```py 
    if value == 0:
```
instead of 
```py 
    if (abs (value) == 0):"
```
you can choose me as your PR reviewer
You would be welcome among the contributors of Shapash!
