### ISSUE TITLE
Unable to install shapash on AWS Sagemaker Notebook instance

### ISSUE THREAD

**Issue by notAmine** [MAIF/shapash#159]
Hello Team,
I'm trying to install shapash in a conda env (default python3) running on AWS Sagemaker notebook instance. I tried running 
!pip install shapash (since shapash is not available on conda) 
but I get this error with the llvmlite dependency.
Full log:
 
`Collecting shapash
  Using cached shapash-1.2.0-py2.py3-none-any.whl (841 kB)
Collecting dash-bootstrap-components==0.9.1
  Using cached dash_bootstrap_components-0.9.1-py3-none-any.whl
Requirement already satisfied: numpy>1.18.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from shapash) (1.19.5)
Collecting dash-core-components==1.13.0
  Using cached dash_core_components-1.13.0-py3-none-any.whl
Collecting dash-table==4.11.0
  Using cached dash_table-4.11.0-py3-none-any.whl
Collecting numba==0.51.2
  Using cached numba-0.51.2-cp36-cp36m-manylinux2014_x86_64.whl (3.1 MB)
Requirement already satisfied: pandas>1.0.2 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from shapash) (1.1.5)
Collecting dash-html-components==1.1.1
  Using cached dash_html_components-1.1.1-py3-none-any.whl
Collecting shap==0.37.0
  Using cached shap-0.37.0-cp36-cp36m-linux_x86_64.whl
Requirement already satisfied: plotly==4.12.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from shapash) (4.12.0)
Collecting dash-renderer==1.8.3
  Using cached dash_renderer-1.8.3-py3-none-any.whl
Collecting dash-daq==0.5.0
  Using cached dash_daq-0.5.0-py3-none-any.whl
Requirement already satisfied: nbformat>4.2.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from shapash) (5.1.2)
Collecting dash==1.17.0
  Using cached dash-1.17.0-py3-none-any.whl
Collecting flask-compress
  Using cached Flask_Compress-1.9.0-py3-none-any.whl (7.3 kB)
Requirement already satisfied: Flask>=1.0.2 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from dash==1.17.0->shapash) (1.1.2)
Requirement already satisfied: future in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from dash==1.17.0->shapash) (0.18.2)
Collecting llvmlite<0.35,>=0.34.0.dev0
  Using cached llvmlite-0.34.0-cp36-cp36m-manylinux2010_x86_64.whl (24.6 MB)
Requirement already satisfied: setuptools in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from numba==0.51.2->shapash) (49.6.0.post20210108)
Requirement already satisfied: six in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from plotly==4.12.0->shapash) (1.15.0)
Requirement already satisfied: retrying>=1.3.3 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from plotly==4.12.0->shapash) (1.3.3)
Requirement already satisfied: scipy in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from shap==0.37.0->shapash) (1.5.3)
Requirement already satisfied: tqdm>4.25.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from shap==0.37.0->shapash) (4.60.0)
Requirement already satisfied: scikit-learn in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from shap==0.37.0->shapash) (0.24.1)
Collecting slicer==0.0.3
  Using cached slicer-0.0.3-py3-none-any.whl (11 kB)
Requirement already satisfied: itsdangerous>=0.24 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from Flask>=1.0.2->dash==1.17.0->shapash) (1.1.0)
Requirement already satisfied: click>=5.1 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from Flask>=1.0.2->dash==1.17.0->shapash) (7.1.2)
Requirement already satisfied: Werkzeug>=0.15 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from Flask>=1.0.2->dash==1.17.0->shapash) (1.0.1)
Requirement already satisfied: Jinja2>=2.10.1 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from Flask>=1.0.2->dash==1.17.0->shapash) (2.11.3)
Requirement already satisfied: MarkupSafe>=0.23 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from Jinja2>=2.10.1->Flask>=1.0.2->dash==1.17.0->shapash) (1.1.1)
Requirement already satisfied: jupyter-core in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from nbformat>4.2.0->shapash) (4.7.1)
Requirement already satisfied: traitlets>=4.1 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from nbformat>4.2.0->shapash) (4.3.3)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from nbformat>4.2.0->shapash) (3.2.0)
Requirement already satisfied: ipython-genutils in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from nbformat>4.2.0->shapash) (0.2.0)
Requirement already satisfied: attrs>=17.4.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>4.2.0->shapash) (20.3.0)
Requirement already satisfied: pyrsistent>=0.14.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>4.2.0->shapash) (0.17.3)
Requirement already satisfied: importlib-metadata in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>4.2.0->shapash) (3.7.0)
Requirement already satisfied: python-dateutil>=2.7.3 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from pandas>1.0.2->shapash) (2.8.1)
Requirement already satisfied: pytz>=2017.2 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from pandas>1.0.2->shapash) (2021.1)
Requirement already satisfied: decorator in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from traitlets>=4.1->nbformat>4.2.0->shapash) (4.4.2)
Requirement already satisfied: brotli in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from flask-compress->dash==1.17.0->shapash) (1.0.9)
Requirement already satisfied: zipp>=0.5 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from importlib-metadata->jsonschema!=2.5.0,>=2.4->nbformat>4.2.0->shapash) (3.4.0)
Requirement already satisfied: typing-extensions>=3.6.4 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from importlib-metadata->jsonschema!=2.5.0,>=2.4->nbformat>4.2.0->shapash) (3.7.4.3)
Requirement already satisfied: threadpoolctl>=2.0.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from scikit-learn->shap==0.37.0->shapash) (2.1.0)
Requirement already satisfied: joblib>=0.11 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from scikit-learn->shap==0.37.0->shapash) (1.0.1)
Installing collected packages: llvmlite, flask-compress, dash-table, dash-renderer, dash-html-components, dash-core-components, slicer, numba, dash, shap, dash-daq, dash-bootstrap-components, shapash
  Attempting uninstall: llvmlite
    Found existing installation: llvmlite 0.35.0
ERROR: Cannot uninstall 'llvmlite'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.`

**Comment by yg79** [comment]
Hello NotAmine,

Within the MAIF Shapash team we do not work on AWS, which is why it is difficult for us to help you. We would still be delighted if Shapash could easily be installed on AWS and would love to have new contributors help us develop the features that are useful to them.

**Comment by yg79** [comment]
However, we have already encountered problems with "llvmlite". Maybe you can freeze your env and post your requirement.txt in this issue: We'll check it
