### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by RukhaiyarS** [MAIF/shapash#190]
While installing following msg was recieved

ollecting shapash
  Using cached shapash-1.3.2-py2.py3-none-any.whl (863 kB)
Requirement already satisfied: numpy>1.18.0 in c:\users\saura\anaconda3\lib\site-packages (from shapash) (1.18.5)
Requirement already satisfied: matplotlib>=3.0 in c:\users\saura\anaconda3\lib\site-packages (from shapash) (3.2.2)
Collecting shap==0.37.0
  Using cached shap-0.37.0-cp38-cp38-win_amd64.whl (377 kB)
Requirement already satisfied: pandas>1.0.2 in c:\users\saura\anaconda3\lib\site-packages (from shapash) (1.0.5)
Requirement already satisfied: dash-html-components==1.1.1 in c:\users\saura\anaconda3\lib\site-packages (from shapash) (1.1.1)
Requirement already satisfied: papermill==2.3.2 in c:\users\saura\anaconda3\lib\site-packages (from shapash) (2.3.2)
Requirement already satisfied: plotly==4.12.0 in c:\users\saura\anaconda3\lib\site-packages (from shapash) (4.12.0)
Requirement already satisfied: dash-renderer==1.8.3 in c:\users\saura\anaconda3\lib\site-packages (from shapash) (1.8.3)
Collecting numba==0.51.2
  Using cached numba-0.51.2-cp38-cp38-win_amd64.whl (2.2 MB)
Requirement already satisfied: dash-core-components==1.13.0 in c:\users\saura\anaconda3\lib\site-packages (from shapash) (1.13.0)
Requirement already satisfied: nbformat>4.2.0 in c:\users\saura\anaconda3\lib\site-packages (from shapash) (5.0.7)
Requirement already satisfied: dash-table==4.11.0 in c:\users\saura\anaconda3\lib\site-packages (from shapash) (4.11.0)
Collecting dash-daq==0.5.0
  Using cached dash_daq-0.5.0-py3-none-any.whl
Requirement already satisfied: nbconvert==6.0.7 in c:\users\saura\anaconda3\lib\site-packages (from shapash) (6.0.7)
Requirement already satisfied: dash-bootstrap-components==0.9.1 in c:\users\saura\anaconda3\lib\site-packages (from shapash) (0.9.1)
Requirement already satisfied: seaborn==0.11.1 in c:\users\saura\anaconda3\lib\site-packages (from shapash) (0.11.1)
Requirement already satisfied: dash==1.17.0 in c:\users\saura\anaconda3\lib\site-packages (from shapash) (1.17.0)
Requirement already satisfied: Flask>=1.0.2 in c:\users\saura\anaconda3\lib\site-packages (from dash==1.17.0->shapash) (1.1.2)
Requirement already satisfied: flask-compress in c:\users\saura\anaconda3\lib\site-packages (from dash==1.17.0->shapash) (1.9.0)
Requirement already satisfied: future in c:\users\saura\anaconda3\lib\site-packages (from dash==1.17.0->shapash) (0.18.2)
Requirement already satisfied: jupyterlab-pygments in c:\users\saura\anaconda3\lib\site-packages (from nbconvert==6.0.7->shapash) (0.1.2)
Requirement already satisfied: mistune<2,>=0.8.1 in c:\users\saura\anaconda3\lib\site-packages (from nbconvert==6.0.7->shapash) (0.8.4)
Requirement already satisfied: jinja2>=2.4 in c:\users\saura\anaconda3\lib\site-packages (from nbconvert==6.0.7->shapash) (2.11.2)
Requirement already satisfied: entrypoints>=0.2.2 in c:\users\saura\anaconda3\lib\site-packages (from nbconvert==6.0.7->shapash) (0.3)
Requirement already satisfied: nbclient<0.6.0,>=0.5.0 in c:\users\saura\anaconda3\lib\site-packages (from nbconvert==6.0.7->shapash) (0.5.3)
Requirement already satisfied: defusedxml in c:\users\saura\anaconda3\lib\site-packages (from nbconvert==6.0.7->shapash) (0.6.0)
Requirement already satisfied: jupyter-core in c:\users\saura\anaconda3\lib\site-packages (from nbconvert==6.0.7->shapash) (4.6.3)
Requirement already satisfied: bleach in c:\users\saura\anaconda3\lib\site-packages (from nbconvert==6.0.7->shapash) (3.1.5)
Requirement already satisfied: traitlets>=4.2 in c:\users\saura\anaconda3\lib\site-packages (from nbconvert==6.0.7->shapash) (5.0.5)
Requirement already satisfied: pygments>=2.4.1 in c:\users\saura\anaconda3\lib\site-packages (from nbconvert==6.0.7->shapash) (2.6.1)
Note: you may need to restart the kernel to use updated packages.
ERROR: Cannot uninstall 'llvmlite'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
Requirement already satisfied: testpath in c:\users\saura\anaconda3\lib\site-packages (from nbconvert==6.0.7->shapash) (0.4.4)
Requirement already satisfied: pandocfilters>=1.4.1 in c:\users\saura\anaconda3\lib\site-packages (from nbconvert==6.0.7->shapash) (1.4.2)
Requirement already satisfied: setuptools in c:\users\saura\anaconda3\lib\site-packages (from numba==0.51.2->shapash) (49.2.0.post20200714)
Collecting llvmlite<0.35,>=0.34.0.dev0
  Using cached llvmlite-0.34.0-cp38-cp38-win_amd64.whl (15.9 MB)
Requirement already satisfied: requests in c:\users\saura\anaconda3\lib\site-packages (from papermill==2.3.2->shapash) (2.24.0)
Requirement already satisfied: click in c:\users\saura\anaconda3\lib\site-packages (from papermill==2.3.2->shapash) (7.1.2)
Requirement already satisfied: tenacity in c:\users\saura\anaconda3\lib\site-packages (from papermill==2.3.2->shapash) (7.0.0)
Requirement already satisfied: tqdm>=4.32.2 in c:\users\saura\anaconda3\lib\site-packages (from papermill==2.3.2->shapash) (4.60.0)
Requirement already satisfied: ansiwrap in c:\users\saura\anaconda3\lib\site-packages (from papermill==2.3.2->shapash) (0.8.4)
Requirement already satisfied: black in c:\users\saura\anaconda3\lib\site-packages (from papermill==2.3.2->shapash) (21.4b2)
Collecting nbformat>4.2.0
  Using cached nbformat-5.1.3-py3-none-any.whl (178 kB)
Requirement already satisfied: pyyaml in c:\users\saura\anaconda3\lib\site-packages (from papermill==2.3.2->shapash) (5.4.1)
Requirement already satisfied: six in c:\users\saura\anaconda3\lib\site-packages (from plotly==4.12.0->shapash) (1.15.0)
Requirement already satisfied: retrying>=1.3.3 in c:\users\saura\anaconda3\lib\site-packages (from plotly==4.12.0->shapash) (1.3.3)
Requirement already satisfied: scipy>=1.0 in c:\users\saura\anaconda3\lib\site-packages (from seaborn==0.11.1->shapash) (1.5.0)
Requirement already satisfied: slicer==0.0.3 in c:\users\saura\anaconda3\lib\site-packages (from shap==0.37.0->shapash) (0.0.3)
Requirement already satisfied: scikit-learn in c:\users\saura\anaconda3\lib\site-packages (from shap==0.37.0->shapash) (0.23.1)
Requirement already satisfied: itsdangerous>=0.24 in c:\users\saura\anaconda3\lib\site-packages (from Flask>=1.0.2->dash==1.17.0->shapash) (1.1.0)
Requirement already satisfied: Werkzeug>=0.15 in c:\users\saura\anaconda3\lib\site-packages (from Flask>=1.0.2->dash==1.17.0->shapash) (1.0.1)
Requirement already satisfied: MarkupSafe>=0.23 in c:\users\saura\anaconda3\lib\site-packages (from jinja2>=2.4->nbconvert==6.0.7->shapash) (1.1.1)
Requirement already satisfied: cycler>=0.10 in c:\users\saura\anaconda3\lib\site-packages (from matplotlib>=3.0->shapash) (0.10.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in c:\users\saura\anaconda3\lib\site-packages (from matplotlib>=3.0->shapash) (2.4.7)
Requirement already satisfied: python-dateutil>=2.1 in c:\users\saura\anaconda3\lib\site-packages (from matplotlib>=3.0->shapash) (2.8.1)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\saura\anaconda3\lib\site-packages (from matplotlib>=3.0->shapash) (1.2.0)
Requirement already satisfied: jupyter-client>=6.1.5 in c:\users\saura\anaconda3\lib\site-packages (from nbclient<0.6.0,>=0.5.0->nbconvert==6.0.7->shapash) (6.1.6)
Requirement already satisfied: nest-asyncio in c:\users\saura\anaconda3\lib\site-packages (from nbclient<0.6.0,>=0.5.0->nbconvert==6.0.7->shapash) (1.5.1)
Requirement already satisfied: async-generator in c:\users\saura\anaconda3\lib\site-packages (from nbclient<0.6.0,>=0.5.0->nbconvert==6.0.7->shapash) (1.10)
Requirement already satisfied: pyzmq>=13 in c:\users\saura\anaconda3\lib\site-packages (from jupyter-client>=6.1.5->nbclient<0.6.0,>=0.5.0->nbconvert==6.0.7->shapash) (19.0.1)
Requirement already satisfied: tornado>=4.1 in c:\users\saura\anaconda3\lib\site-packages (from jupyter-client>=6.1.5->nbclient<0.6.0,>=0.5.0->nbconvert==6.0.7->shapash) (6.0.4)
Requirement already satisfied: pywin32>=1.0 in c:\users\saura\anaconda3\lib\site-packages (from jupyter-core->nbconvert==6.0.7->shapash) (300)
Requirement already satisfied: ipython-genutils in c:\users\saura\anaconda3\lib\site-packages (from nbformat>4.2.0->shapash) (0.2.0)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in c:\users\saura\anaconda3\lib\site-packages (from nbformat>4.2.0->shapash) (3.2.0)
Requirement already satisfied: attrs>=17.4.0 in c:\users\saura\anaconda3\lib\site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>4.2.0->shapash) (19.3.0)
Requirement already satisfied: pyrsistent>=0.14.0 in c:\users\saura\anaconda3\lib\site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>4.2.0->shapash) (0.16.0)
Requirement already satisfied: pytz>=2017.2 in c:\users\saura\anaconda3\lib\site-packages (from pandas>1.0.2->shapash) (2020.1)
Requirement already satisfied: textwrap3>=0.9.2 in c:\users\saura\anaconda3\lib\site-packages (from ansiwrap->papermill==2.3.2->shapash) (0.9.2)
Requirement already satisfied: toml>=0.10.1 in c:\users\saura\anaconda3\lib\site-packages (from black->papermill==2.3.2->shapash) (0.10.1)
Requirement already satisfied: pathspec<1,>=0.8.1 in c:\users\saura\anaconda3\lib\site-packages (from black->papermill==2.3.2->shapash) (0.8.1)
Requirement already satisfied: regex>=2020.1.8 in c:\users\saura\anaconda3\lib\site-packages (from black->papermill==2.3.2->shapash) (2020.6.8)
Requirement already satisfied: mypy-extensions>=0.4.3 in c:\users\saura\anaconda3\lib\site-packages (from black->papermill==2.3.2->shapash) (0.4.3)
Requirement already satisfied: appdirs in c:\users\saura\anaconda3\lib\site-packages (from black->papermill==2.3.2->shapash) (1.4.4)
Requirement already satisfied: packaging in c:\users\saura\anaconda3\lib\site-packages (from bleach->nbconvert==6.0.7->shapash) (20.4)
Requirement already satisfied: webencodings in c:\users\saura\anaconda3\lib\site-packages (from bleach->nbconvert==6.0.7->shapash) (0.5.1)
Requirement already satisfied: brotli in c:\users\saura\anaconda3\lib\site-packages (from flask-compress->dash==1.17.0->shapash) (1.0.9)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\saura\anaconda3\lib\site-packages (from requests->papermill==2.3.2->shapash) (1.25.9)
Requirement already satisfied: idna<3,>=2.5 in c:\users\saura\anaconda3\lib\site-packages (from requests->papermill==2.3.2->shapash) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\saura\anaconda3\lib\site-packages (from requests->papermill==2.3.2->shapash) (2020.6.20)
Requirement already satisfied: chardet<4,>=3.0.2 in c:\users\saura\anaconda3\lib\site-packages (from requests->papermill==2.3.2->shapash) (3.0.4)
Requirement already satisfied: joblib>=0.11 in c:\users\saura\anaconda3\lib\site-packages (from scikit-learn->shap==0.37.0->shapash) (0.16.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\saura\anaconda3\lib\site-packages (from scikit-learn->shap==0.37.0->shapash) (2.1.0)
Installing collected packages: nbformat, llvmlite, numba, shap, dash-daq, shapash
  Attempting uninstall: nbformat
    Found existing installation: nbformat 5.0.7
    Uninstalling nbformat-5.0.7:
      Successfully uninstalled nbformat-5.0.7
  Attempting uninstall: llvmlite
    Found existing installation: llvmlite 0.33.0+1.g022ab0f

**Comment by ThibaudReal** [comment]
Hello @RukhaiyarS ,
Reading your message it seems that Shapash was correctly installed : 
```
Installing collected packages: nbformat, llvmlite, numba, shap, dash-daq, shapash
```

But I may be wrong. Were you able to use the Shapash library correctly ? 
You can try to execute the tutorials and see if an error occurs.
If you encounter an error you may want to try in a new environment to see if this still happens.

 Please let us know if you have any problem using Shapash.
