### ISSUE TITLE
WebApp Display Bug

### ISSUE THREAD

**Issue by yg79** [MAIF/shapash#227]
the options button does not display well in the webapp demo (https://shapash-demo2.ossbymaif.fr/)
<img width="328" alt="Capture d’écran 2021-07-30 à 11 26 21" src="https://user-images.githubusercontent.com/41585787/127634773-6e86c9a6-3b5f-40a4-9bc3-80907ddda812.png">

- Are you using Mac, Linux or Windows? Mac book Pro 2,6 GHz Intel Core i5 double cœur / Le MacBook Pro (Retina, 13 pouces, mi-2014) / MacOS Catalina 10.15.7
- Google Chrome: Version 92.0.4515.107 (Build officiel) (x86_64)

**Comment by guerinclement** [comment]
Fixed.
