### ISSUE TITLE
Is shapash model agnostic?

### ISSUE THREAD

**Issue by golubovic** [MAIF/shapash#228]
Hi,

Great project! I have seen the examples including the ScikitLearn model, my question is, is this framework model agnostic, and if not are Torch and TFlow models supported? Listing compatibility with models will  I hope greatly accelerate adoption.

Thanks,
Mladen

**Comment by yg79** [comment]
shapash is not yet compatible with deeplearning frameworks like TF and Pytorch.
We will try to work on it in the coming months, We are also open to all contributions: you are welcome
