### ISSUE TITLE
Stability metric - SmartPlotter - Analyze stability of SHAP values in a new created plot

### ISSUE THREAD

**Issue by Francesco-Marini** [MAIF/shapash#234]
**Description of Problem**:
In order to get a better confidence on SHAP values and identify situations where their interpretation should be taken with a grain of salt, a new metric about _local stability_. is proposed. This stability metric may be a way to increase confidence on the interpretation of SHAP values.
For an instance and its "neighbours" (in terms of both feature space and model output), we look at the variability of SHAP values : in theory, we would expect them to be close for similar instances. If not, one might want to be careful when interpreting those values.

**Overview of the Solution**:
1. The input of this method could be either a single instance or a set of instances for which we want to analyze the neighbourhood.

2. All intermediate methods required to compute this plot would be stored in a stability.py file in the utils folder : because no dependencies are required (except numpy, pandas, sklearn) and no strong overlap exists with the other files, I was thinking to create a separate file for those methods. An alternative could be to put everything in the existing utils.py file.

3. These intermediate methods would be called from the SmartExplainer object (through a _compute_features_stability_ method) and the result would be available as a new attribute (similarly to how actual _features_imp_ attribute is calculated). This attribute could be a list of arrays that will be displayed on the graph.

4. Finally, a plot function would be created in the SmartPlotter object and call _compute_features_stability_ each time a user wants to display the metric. The calculation of the metric would need to be done every time a plot is requested. By doing so, we ensure the compile method is not overloaded.

**Note:** 
- This method is based on what already exists. Thus, access to contributions and model will be done via existing attributes
- As multi-class classification is not handled yet, an error will be displayed if we were in such situation (using self.state attribute ?)

**Comment by yg79** [comment]
Nice Issue Francesco! I can't wait to use this new plot!
to check multi-class classification, you can use self._case and self._classes
