### ISSUE TITLE
Compacity metric - SmartPlotter - Determine how a well-chosen subset of features approximate the model

### ISSUE THREAD

**Issue by Francesco-Marini** [MAIF/shapash#241]
**Description of Problem**:
The number of features greatly affects explainability. Two plots are proposed to illustrate that and decide how many features are necessary to drive the model. To do this, the output of the ML model containing all features is compared against the output of the model containing only the top features selected by the explainability method.

The two plots highlight the following ideas:
- Determine the minimum number of features needed for the prediction of the interpretability method to be close enough to the one obtained with all features.
- Contraposition : determine how close we get to the output with all features by using only a subset of them

**Overview of the Solution**:
1. The input of this method could be either a selection of data points chosen by the user, or a random sample from the dataset

2. Similarly to the stability plot, all intermediate methods will be stored in a separate .py file (Should we store all these intermediate methods in the same file that will contain all metrics-based plots ? And rename the `stability.py` file into something like `explanation_metrics` ?)

3. Those intermediate methods will be computed in a `compute_compacity` method in the SmartExplainer object

4. Finally, the `compute_compacity`method will be called directly by the SmartPlotter object. We could possibly add a `force`parameter to avoid the computation if the random sampling is selected

**Note:** 
- As multi-class classification is not handled, an error will be displayed if we were in such situation

**Comment by yg79** [comment]
👍
