### ISSUE TITLE
Add support for Python 3.10

### ISSUE THREAD

**Issue by quassy** [MAIF/shapash#293]
**Description of Problem**: Currently only Python 3.6 to 3.9 seem to be officially supported.

**Overview of the Solution**: Drop support for 3.6 which is EOL, add support of 3.10. Check dependencies, run tests, adapt GitHub workflow to 3.10, etc.

**Comment by ThomasBouche** [comment]
Thank you for the issue.
Indeed, it would be great to remove 3.6 and add 3.10
We will see about adding this change to our future changes or you can also propose a pull request

**Comment by garaud** [comment]
Hi,

I'm also interested in the support for Python 3.10. I saw that there is a **draft** Pull Request @ThomasBouche 
Is it ready to merge or there is some remaining work on it? Do you need any help?

Thanks

**Comment by ThomasBouche** [comment]
Hi, 
To support Python 3.10, we have problems with dependency compatibility:
- ACV (https://github.com/salimamoukou/acv00) does not support python 3.10, the maintainer was working on it before the summer. 
- At the moment, there are compatibility issues between the latest version of Numba, and Numpy (https://github.com/numba/numba/issues/8263) which should be resolved soon. I can't find versions of these libs that work well on all versions of Python, I hope the next version of numba will solve problems.

I will test again when Numba makes a new release.

**Comment by garaud** [comment]
Thank you @ThomasBouche for your answer. It seems quite tricky the numba/numpy versions dependency.

**Comment by ThomasBouche** [comment]
Hi,
As you can see, this issue is close, you can now use Shapash with a Python 3.10 !

**Comment by garaud** [comment]
@ThomasBouche Great!!

Thanks
