### ISSUE TITLE
Bug in webapp display for classification

### ISSUE THREAD

**Issue by amorea04** [MAIF/shapash#357]
The web app display of the top area (title......) is not optimal when a classification model is provided to shapash.

**Python version** : 3.9

**Shapash version** : 2.0.0

**Operating System** : windows (web app display: edge)

![bug_shapash_report](https://user-images.githubusercontent.com/36231668/166924654-0470ae0a-f05e-4e93-9e18-aa034f295406.PNG)

**Comment by ThomasBouche** [comment]
Thanks for pointing it out, we will fix it
