### ISSUE TITLE
explanation with lime backend returns 'lime_tabular' not defined error

### ISSUE THREAD

**Issue by thlevy** [MAIF/shapash#360]
Hello,
I tried to build an explanation with lime backend but got the following error:
My code:
```
from shapash.explainer.smart_explainer import SmartExplainer
import lime.lime_tabular
xpl = SmartExplainer(model=rf, backend='lime')
xpl.compile(x=X_i)
```
=>
```
File c:\Users\X\AppData\Local\Programs\Python\Python39\lib\site-packages\shapash\backend\lime_backend.py:39, in LimeBackend.run_explainer(self, x)
...
---> [39](file:///c%3A/Users/X/AppData/Local/Programs/Python/Python39/lib/site-packages/shapash/backend/lime_backend.py?line=38) explainer = lime_tabular.LimeTabularExplainer(
...

NameError: name 'lime_tabular' is not defined
```

I am using:
**Python version** : 3.9.12
Lime version: 0.2.0.1

**Shapash version** :  2.0.1

**Operating System** : Windows 10

Should I import or install a particular lime version to make it work?
Thanks,
Thomas

**Comment by SebastienBidault** [comment]
Hello Thomas,

I tried with the same configuration [tuto](https://github.com/MAIF/shapash/blob/master/tutorial/backend/tuto-backend-01.ipynb) , i just change acv to lime and it worked well for me.

Have you tried lime without shapash to make sure Lime is correctly installed on your kernel ?

Sébastien

**Comment by thlevy** [comment]
Hello Sébastien,
I checked that Lime (without shapash) is correctly working with a simple test. But, for some reason that I can't explain, I was not able to reproduce the initial issue. Probably, there was a dependency updated when re-installing shapash. So, I think that we can close the issue.
Thanks for your support,
Thomas
