### ISSUE TITLE
Consistency : Display contributions' differences across each feature

### ISSUE THREAD

**Issue by Francesco-Marini** [MAIF/shapash#362]
**Description of Problem**:
As different explainability methods often provide different explanations, we provide a new graph that helps investigating where those differences are located in the data

**Overview of the Solution**:
A new plotly graph is generated. It calculates the explanations of 2 different methods and compares their difference across each feature. In particular, it takes the form of a violin plot (one violin per feature). Violins will be ranked according to feature importance (mean of absolute values of contributions)

All methods as well as the plot itself will be implemented in the `consistency.py` file.

**Comment by ThomasBouche** [comment]
Hi,

It looks very interesting.
Yes, let's keep methods and plots in consistency.py
Looking forward to your contribution !
