### ISSUE TITLE
Add tab that contains dataset filters

### ISSUE THREAD

**Issue by FlorineGreciet** [MAIF/shapash#384]
This tab contains buttons to add or reset filters on the data set. The format of the filters is adapted according to the type of variable selected. It is possible to select as many new filters as you want. 
You must click on the Apply Filter button for the filters to be applied to the table and charts.
If you delete a filter using the (X) button, it is necessary to click on the Apply Filter button again for the table and charts to be updated.

**Comment by ThomasBouche** [comment]
![image](https://user-images.githubusercontent.com/53937041/196209467-40ca818b-2ae7-4a32-b60d-7f906b78a645.png)
