### ISSUE TITLE
Adapt the labels of graphs according to their size

### ISSUE THREAD

**Issue by FlorineGreciet** [MAIF/shapash#385]
If the size of a label on the x-axis is greater than 10, only the first three and last three characters are displayed, separated by "...". The same applies to the Y axis when the size of a label is greater than 30.
When you click on the zoom button, the labels appear in full

**Comment by ThomasBouche** [comment]
![image](https://user-images.githubusercontent.com/53937041/196209057-7b46018a-8eec-4996-9ca1-72fb30791516.png)
![image](https://user-images.githubusercontent.com/53937041/196209117-aa1a20f3-e5e0-42e3-b05a-3ae1f54dfe20.png)
