### ISSUE TITLE
Create to tab which contains prediction picking graph and connexion with other graph

### ISSUE THREAD

**Issue by FlorineGreciet** [MAIF/shapash#388]
The prediction selection graph is now available in a new tab in shapash. This graph is connected to the data table and the other graphs. The user can select a subset in this graph to view only that subsample in the table and graphs. To deselect the subset, the user must double-click on the graph.

**Comment by ThomasBouche** [comment]
![image](https://user-images.githubusercontent.com/53937041/196208176-d8905615-b567-4144-9258-acfa4db291bc.png)
![image](https://user-images.githubusercontent.com/53937041/196208226-a6928520-5138-4868-a545-b93536fed96d.png)
