### ISSUE TITLE
Using ACV algorithm to compute contributions for coalitions of features

### ISSUE THREAD

**Issue by cyrlemaire** [MAIF/shapash#410]
**Description of Problem**:

Shapash can use ACV as a backend to compute feature contribution. ACV has the advantage of being able to directly compute shapley values for coalition of features. In that case, their are no individual contributions for the individual features, just one for the coalition

Shapash already has a features_groups argument for the smart explainer that sum contributions of features for the group (as it should for SHAP or LIME backend). Nevertheless, the coalition property of ACV is not used in that case.

**Overview of the Solution**:

The feature_groups allows the user to group contributions by summing them but also to display individual contributions for the group (like in the webapp).

If we use the feature_groups argument to compute contributions for coalitions, this won't be possible for ACV. To keep the app as it is, we should add a new argument (like "acv_feature_coalition") that can be used only with acv as a backend and used in the acv_tree algorithm in acv_backend.py. 

shapley_values = acvtree.shap_values(X, C=acv_feature_coalition)

Also I would suggest letting the user choose between regular shapley values computed with the acvtree.shap_values and the active shapley values computed with acvtree.shap_values_acv_adap

**Comment by ThomasBouche** [comment]
Thank you for your issue, 

The description is very clear! Good idea the acv_feature_coalition parameter !

**Comment by guillaume-vignal** [comment]
ACV has been removed because no development has been done since August 2022
