### ISSUE TITLE
Support for scikit-learn 1.2.1

### ISSUE THREAD

**Issue by vishal-unissant** [MAIF/shapash#435]
**Description of Problem**:

The scikit-learn supported by Shapash is outdated and needs to be upgraded to scikit-learn version > 1.2.0 (1.2.1 is the latest)

**Overview of the Solution**:

**Examples**:

**Blockers**:

**Definition of Done**:

**Comment by ThomasBouche** [comment]
Hi, 

Thanks for your issue, 
We upgrade the version of sklearn in this pull request:
https://github.com/MAIF/shapash/pull/421

But we haven't made the release for the pypi installation yet. We will do it in the next few days

**Comment by ThomasBouche** [comment]
This issue is fix on the new release Shapash 2.3.x
