### ISSUE TITLE
Web app bug dataframe to dict

### ISSUE THREAD

**Issue by hippograndet** [MAIF/shapash#449]
Code:
            import xgboost
            import pandas
            from shapash import SmartExplainer
            
            X = [
                [1, 1, 1],
                [2, 2, 2],
                [3, 3, 3]
            ]
            y = [1, 1, 2]
            
            rgr = xgboost.XGBRegressor()
            rgr.fit(X, y)
            
            xpl = SmartExplainer(
              model=rgr
            )
            xpl.compile(
                x=pandas.DataFrame(X),    
                y_target=pandas.Series(y)
            )
            app = xpl.run_app()

Error:
          ValueError: orient 'rows' not understood

On call xpl.run_app(), shapash/webapp/smart_app.py, 
line 354: for row in self.dataframe.to_dict('rows')

According to pandas documentation 'rows' isn't and hasn't ever been a valid value for pd.DataFrame.to_rows function

**Python version** :
3.9.12

**Shapash version** :
2.3.0

**Pandas version**
2.0.0

**Operating System** :
macOS 11.6.6

**Comment by hippograndet** [comment]
Should work for: 
for row in self.dataframe.to_dict('index').values()

**Comment by ThomasBouche** [comment]
Hi, Thank you for your issue and for your proposal for a fix !

We have other bugs with version 2.0.0 of pandas, we will solve them
