### ISSUE TITLE
How can I extract the plot data from `xpl.plot.features_importance()`?

### ISSUE THREAD

**Issue by AkshitChugh787** [MAIF/shapash#450]
I am on Shapash version 2.3.0
By running the command `to_pandas()`, I get the `summary_df` for all the local data points like 

> features_1, contribution_1 ... features_n, contribution_n

I want the importance of the global features from my machine learning model like I get the plot by running the command `xpl.plot.features_importance()`.
What is the method or function to get the global **Features Importance** data points?

Thanks

**Comment by ThomasBouche** [comment]
Hi, 
you can have features importance with:
```
xpl.features_imp
```

is this what you want?

**Comment by AkshitChugh787** [comment]
Thanks, it worked!
