### ISSUE TITLE
References and modifications of self in smartapp create unwanted behavior

### ISSUE THREAD

**Issue by MLecardonnel** [MAIF/shapash#455]
References and modifications of self in smartapp create unwanted behavior when several users on the same app.
Those modifications must be deleted.

**Python version** :3.9

**Shapash version** :2.3.3

**Operating System** :Linux

**Comment by ThomasBouche** [comment]
Thank you issue. 

We will solve the compatibility problems between shapash and numpy 1.24.
But there will still be the incompatibility issues with shap. 
So you will always have to install a version of numpy lower than 1.24.

We will see with the shapash team how we will fix this issue if shap does not answer it. And we are interested in feedback to manage these incompatibility issues between our dependencies
