### ISSUE TITLE
Python 3.11 support

### ISSUE THREAD

**Issue by ShubhamBhut** [MAIF/shapash#458]
Request to add support for python 3.11

**Comment by ThomasBouche** [comment]
Hi, thanks for your issue, 

To add support for Python 3.11 in Shapash, its main dependencies (shap, lime, acv,...) must be compatible with Python3.11. 

We'll see how to add support with some dependencies that don't seem to be maintained anymore

**Comment by realabja** [comment]
Hi Guys I see that shap is supporting 3.11 [0.42.0](https://github.com/shap/shap/releases/tag/v0.42.0), is there any other blockers?

**Comment by ThomasBouche** [comment]
Hello, thanks for the reminder,

Since the new shap maintenance and the choice to remove the "acv-exp" dependency that wasn't maintained, we can go to 3.11.

We'll do a release tomorrow or next week.

In the meantime, you can always clone or fork the project and install shapash with:
```
pip install -e .
```
