### ISSUE TITLE
trouble with XGBoosRegressor

### ISSUE THREAD

**Issue by Zeusg121** [MAIF/shapash#462]
Hey there and thank you for using Issue Tracker!

Do the checklist before filing an issue:

- Is this something you can debug and fix? Send a pull request ! Bug fixes and documentation fixes are welcome.
- Have a usage question ? Ask your question on StackOverflow. We use StackOverflow for usage question and GitHub for bugs.

None of the above, create a bug report

Make sure to add all the information needed to understand the bug so that someone can help. If the info is missing we'll add the 'Needs more information' label and close the issue until there is enough information.

- Provide a minimal code snippet example that reproduces the bug.
- Provide screenshots where appropriate
- What's the version of Python you're using ?
- Are you using Mac, Linux or Windows?

**Python version** : 3.1

**Shapash version** : lastest

**Operating System** : Windows 10 and google colab
Good evening, I'm trying to use shapash, when I use XGBoostRegressor I get this error: /usr/local/lib/python3.10/dist-packages/xgboost/core.py:122: UserWarning:

ntree_limit is deprecated, use `iteration_range` or model slicing instead.
I would like to know how to solve this problem thank you very much

**Comment by ThomasBouche** [comment]
Hi, 

Can you give us your version of xgboost?

**Comment by guillaume-vignal** [comment]
Hi @Zeusg121,
Can you give us also your shap version ?
Your problem seems to be related to: https://github.com/slundberg/shap/issues/2984
And so you can upgrade your version of Shap (0.42) to solve the problem.
Have a nice day.
