### ISSUE TITLE
Show how to use alternative shaps (e.g. fasttreeshap, fastshap)

### ISSUE THREAD

**Issue by eafpres** [MAIF/shapash#465]
**Description of Problem**:
There are some other shap packages that improve performance etc.  An example is fasttreeshap, another is fastshap. It's unclear how to configure these for use in Shapash.

**Overview of the Solution**:
One solution is a small addition to the backends tutorial showing how to use e.g. fasttreeshap or fastshap.  

**Examples**:
I tried to use: 
```
custom_backend = fasttreeshap.TreeExplainer(model = model, algorithm = "auto", njobs = -1)
```

but it fails with unknown backend.

**Blockers**:

**Definition of Done**:
Updated tutorial docs

**Comment by ThomasBouche** [comment]
Hi,
Thanks for your issue,

I add a tutorial for use Fasttreeshap and you can use another backend with the similar method.
Does this tutorial help you use Fasttreeshap and shapash?

**Comment by eafpres** [comment]
@ThomasBouche This looks great, thanks!  Now I understand how to substitute the contributions.
