### ISSUE TITLE
Installation from pip is not working

### ISSUE THREAD

**Issue by anirban-ray-publicis-sapient** [MAIF/shapash#502]
Hi, I'm on macOS Ventura 13.6, and trying to install `shapdash` using `pip`. It's failing with following error:

```shell
❯ python -V
Python 3.10.13
❯ pip install shapdash
ERROR: Could not find a version that satisfies the requirement shapdash (from versions: none)
ERROR: No matching distribution found for shapdash
```

I am facing same issue in Ubuntu docker as well.

**Comment by ThomasBouche** [comment]
The repo name is ```shapash```, not shapdash.

shapdash might have been a good name :)
