### ISSUE TITLE
Bug in interaction_plot with a catboost model

### ISSUE THREAD

**Issue by ThomasBouche** [MAIF/shapash#511]
```
xpl.plot.top_interactions_plot(nb_top_interactions=5)
```
![image](https://github.com/MAIF/shapash/assets/53937041/8f60eb5f-d555-4b33-b293-58f30e72e16c)

catboost version : 1.2.2
shap version : 0.42.1
shapash version :2.3.7

**Python version** :3.10

**Shapash version** :2.3.7

**Operating System** :Linux

**Comment by MLecardonnel** [comment]
The error comes from shap that does not compute the interaction values with the catboost method. Corresponding Issue here: https://github.com/shap/shap/issues/3416

**Comment by MLecardonnel** [comment]
Fix in shap 0.44.1 release : https://github.com/shap/shap/pull/3459
