### ISSUE TITLE
Shapash icon has been replaced by dash icon in the webapp

### ISSUE THREAD

**Issue by MLecardonnel** [MAIF/shapash#594]
![image](https://github.com/user-attachments/assets/8d8ad807-e2b1-4f53-b8b1-6cdc9ff0507f)

**Comment by tbloron** [comment]
Le fichier **favicon.ico** dans **shapash/webapp/assets** n'est pas inclus dans le package shapash au build. Le fichier **pyproject.toml** doit être complété.
