### ISSUE TITLE
Shapash available with python 3.8

### ISSUE THREAD

**Issue by AmirMK** [MAIF/shapash#97]
tried to install with: pip install shapash

Error: Could not find a version that satisfies the requirement shamash (from versions: none)
Error: No matching distribution found for shapash

**Comment by yg79** [comment]
Shapash available with python 3.6 / 3.7 (3.8 coming soon --> in a few minutes!!).

If you are working with jupyter, use the following commands in a terminal to create a 3.7 environment:

conda create shpenv python=3.7
source activate shpenv
pip install shapash

**Comment by yg79** [comment]
Shapash Available with python 3.8, you can check
