### ISSUE TITLE
ValueError:

### ISSUE THREAD

**Issue by 321HG** [MAIF/shapash#99]
Could you help me, can this only handle two categories?

ValueError:   Length of list of contributions parameter is not equal to the number of classes in the target.  Please check model and contributions parameters.

**Comment by yg79** [comment]
We just set up a gitter: Can you please chat with the Shapash team for a better understanding of the bug
-> please Click on the gitter badge at the top of Readme.md and post your msg, we will answer it ;-) Thanks
